#!/usr/bin/perl

use strict;
use warnings;

use CommandLine::Files;

my $VERSION = "1.00";

my $usage = "
\tUsage: 
\t    noblank [ -r ] [ -i ] [ -t -tl -tr -n -l ] myfile.txt [ files... ]
\tOr:
\t    someotherprogram | noblank

\tTakes myfile.txt or stdin and prints it to stdout without any blank lines.

\t -t will make noblank trim whitespace off the left and right of lines as well.
\t -tl and -tr will make noblank trim whitespace off only the left OR right of lines, respectively.

\t -n will make noblank remove only lines that are a single end of line character (\\n).  If there is even a single space or tab, the line will remain.
\t -l will leave blank lines.  This may be handy in conjuction with one of the trim options if you wish to leave blank lines, but trim whitespace around lines.
\t     Obviously if you do this, lines consisting of only spaces and tabs will remain, however they will be trimmed down to just an end of line character (\\n)
\t     regardless of which trim option you choose.

\t -r to recursively process text files found in directories.

\t -i to edit the files in place.  Rather than printing the contents of the files to stdout, the files will be modified and saved on disk with the blank lines stripped.
\t    Use this option with care.

\t -v or --version prints the version number.

";

my %args = map { $_ => 1} @ARGV;
print "Version $VERSION\n" and exit( 0 ) if exists $args{ "-v" } or exists $args{ "--version" };

my @files = getfiles( $usage );
%args = map { $_ => 1} @ARGV;

print "Input was STDIN but -i was specified.  Cannot edit files in place on disk when input is STDIN.\n" and exit(1) if exists $args{"-i"} and $CommandLine::Files::InputWasSTDIN;

foreach my $file ( @files ) {
    my @lines = ( );

    open( FILE, $file ) or die "Failed to open file $file.  Error: $!";
    push( @lines, $_ ) while( <FILE> );
    close( FILE );

    # Killing blank lines
    if( exists( $args{"-n"} ) ) {
        s/^\n$// foreach @lines;
    } elsif( exists( $args{"-l"} ) ) {
        # Do Nothing.
    } else {
        s/^\s*$//g foreach @lines;
    }
 
    # Trimming white space.
    if( exists( $args{"-t"} ) ) {
        s/^[^\S\n]*// foreach @lines;
        s/[^\S\n]*$// foreach @lines;
    } elsif( exists( $args{"-tl"} ) ) {
        s/^[^\S\n]*// foreach @lines;
    } elsif( exists( $args{"-tr"} ) ) {
        s/[^\S\n]*$// foreach @lines;
    }
 
    if( exists( $args{"-i"} ) ) {
        open( FILE, "> $file" ) or die "Failed to open file $file.  Error: $!";
        print FILE @lines;
        close( FILE );
    } else {
        print @lines;
    }
}



